name: ADS
services:
    oracle:
        container_name: oracle-db
        ports:
            - 1521:1521
            - 5500:5500
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        environment:
            - ORACLE_PWD=System123
        volumes:
            - ./oracle/oradata:/opt/oracle/oradata
            - ./data:/home/oracle/data
        image: container-registry.oracle.com/database/express:21.3.0-xe
